# На каком порту стартует приложение
server:
    port: 8084

# Настройки логирования
logging:
    level:
        com.example.demo: debug
    file:
        name: logs/dev.log

# Настройки БД
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:15434/university_dev
        username: admin_dev
        password: 5678
    jpa:
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml
